### ISSUE TITLE
About sparsity regularization

### ISSUE THREAD

**Issue by Yanxingang** [Eric-mingjie/network-slimming#1]
Thank you for your sharing. I have a question about sparsity regulization. 
As is shown in the formula (1) in the paper, g(s) is added in the loss function. But in the code, I don't find g(s) in the loss funtion. I only find the additional gradient about scaling factor is added to original gradient.
Could you show me where you add the g(s) to the loss function in the code?

**Comment by Yanxingang** [comment]
Sorry, now I understand.

**Comment by jsliu17** [comment]
Hello, I want to ask why the loss function does not include sparse constraints, although updating the scaling factor does make the BN layer sparse. Thank you! @Yanxingang
