### ISSUE TITLE
vgg_prune.py

### ISSUE THREAD

**Issue by 20victor12** [Eric-mingjie/network-slimming#16]
hey Eric. i got this error during pruning , can you suggest me how should i handle it. Thanks

Traceback (most recent call last):
  File "vggprune.py", line 73, in <module>
    mask = weight_copy.abs().gt(thre).float()
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

**Comment by cardwing** [comment]
In my case, replacing `mask = weight_copy.gt(thre).float().cuda()` with `mask = weight_copy.abs().gt(thre.cuda()).float().cuda()` works.

**Comment by ningscapr** [comment]
Thanks @cardwing, it works!
