### ISSUE TITLE
剪枝程序vggprune.py遇见的问题

### ISSUE THREAD

**Issue by xuemo188** [Eric-mingjie/network-slimming#23]
Traceback (most recent call last):
File "vggprune.py", line 73, in 
mask = weight_copy.gt(thre).float().cuda()
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #2 'other'
我用的环境是python3.6 torch0.4.1

**Comment by Eric-mingjie** [comment]
Use [pytorch 0.3.1](https://github.com/Eric-mingjie/network-slimming#dependencies).

**Comment by xuemo188** [comment]
![image](https://user-images.githubusercontent.com/55520460/65220357-2a1a9400-daed-11e9-80e1-31210ba95df9.png)
您好，我使用了pytorch0.3.1还是存在程序问题vggprune.py
AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/home/maxq/yx/yu/pytorch0.3.1/lib/python3.6/site-packages/torch/_utils.py'>

**Comment by Eric-mingjie** [comment]
This is not a problem of our code. This is because your pretrained models are not trained in Pytorch 0.3.1. See [here](https://discuss.pytorch.org/t/question-about-rebuild-tensor-v2/14560/3).
