### ISSUE TITLE
请问怎么统计inference的时间？

### ISSUE THREAD

**Issue by alanMachineLeraning** [Eric-mingjie/network-slimming#26]
satrt_time = time.time()
output = model(data)
end_time = time.time()
total_time+=(end_time-satrt_time)
为什么我这样统计，剪枝之后inference速度和不剪枝没说明区别，并没有明显提高？

**Comment by Eric-mingjie** [comment]
1. 你用的网络和prune ratio是什么？从这几行代码里我看不出来，没法帮你分析
2. 在[原paper](https://arxiv.org/pdf/1708.06519.pdf)附录B里有对wall clock time的分析
