### ISSUE TITLE
gamma 稀疏问题

### ISSUE THREAD

**Issue by OMG59E** [Eric-mingjie/network-slimming#32]
你好，我训练完vgg16后发现 所有 gamma的值大小从0.1-0.8，好像并不稀疏

**Comment by Eric-mingjie** [comment]
你训练时有加sparisty吗

**Comment by OMG59E** [comment]
caffe 训练的 在scale层加了 l1正则

**Comment by OMG59E** [comment]
> 你训练时有加sparisty吗

用的代码 https://github.com/eezywu/Caffe-Network-Slimming
