### ISSUE TITLE
关于剪枝之后结构的调整

### ISSUE THREAD

**Issue by TerryLoveMl** [Eric-mingjie/network-slimming#33]
你好，非常感谢你的工作，我有个问题，对于network-slimming来讲，剪枝之后重新调整结构，使其更加轻量化，是否可行？

**Comment by Eric-mingjie** [comment]
我不太懂`简直后重新调整结构`具体指一个什么样的步骤?

**Comment by TerryLoveMl** [comment]
非常感谢你的回复，我的疑惑是剪枝之后，是否可以调整卷积的方式，使其计算更加有效率？

**Comment by Eric-mingjie** [comment]
什么叫卷积的方式?

**Comment by TerryLoveMl** [comment]
我复现的是对resnet剪枝的代码，剪枝之后，我想参考人工设计轻量化的网络，比如mobilenetv2，将剪枝之后的网络的普通卷积替换成深度卷积，不知道这样是否可行？

**Comment by Eric-mingjie** [comment]
理论上应该不行吧，slimming剪枝的是filter,剪枝完了之后仍然是全卷积，并不是group convolution。

**Comment by TerryLoveMl** [comment]
谢谢你对我问题的回答，非常友好的博主，祝以后天天开心。
