### ISSUE TITLE
densenet: growthRate & n

### ISSUE THREAD

**Issue by bl166** [Eric-mingjie/network-slimming#4]
https://github.com/Eric-mingjie/network-slimming/blob/0b2f7431dc04e1c04744283aa4ac6524cee48b25/models/densenet.py#L72

Should the 12 here be replaced with growthRate, and the one in line 73 with n?

**Comment by Eric-mingjie** [comment]
Hi, Thanks for your interest in our code! Your suggestions are right.
For DenseNet, the code in this repository guarantees the use of DenseNet-40 as used in the original paper. Feel free to change the code to apply to DenseNet with different depths.
