### ISSUE TITLE
为什么剪枝生成的tar模型压缩包打不开啊？无法解压，显示损坏

### ISSUE THREAD

**Issue by pingzi5233** [Eric-mingjie/network-slimming#47]
如题，不知有人遇到这种情况吗？
我剪枝后生成的模型tar压缩包打不开，显示损坏
![image](https://user-images.githubusercontent.com/48909056/82886322-fabfff00-9f78-11ea-8596-dacf29a98a09.png)

**Comment by Eric-mingjie** [comment]
这个不需要打开，只需要torch.load就行

**Comment by pingzi5233** [comment]
嗯嗯好的，谢谢了
