### ISSUE TITLE
python vggprune.py

### ISSUE THREAD

**Issue by fanbinqi** [Eric-mingjie/network-slimming#5]
when i run the file of vggprune.py, there's a fault: 'unexpected key "module.feature.0.weight" in state_dict'~
i think that's the model's name is wrong. what i should do?

**Comment by Eric-mingjie** [comment]
Could you share more details about the fault? For example, the traceback of the fault. It would be more helpful for us to look into your problem.

**Comment by fanbinqi** [comment]
first i run python main.py --dataset cifar10 --arch vgg --depth 19, and then python main.py -sr --s 0.0001 --dataset cifar10 --arch vgg --depth 19
i got two file, checkpoint.pth.tar and model_best.pth.tar. 
run python vggprune.py, i set check.pth.tar is the model path and get : 

=> loading checkpoint './logs/checkpoint.pth.tar'
Traceback (most recent call last):
  File "vggprune.py", line 43, in <module>
    model.load_state_dict(checkpoint['state_dict'])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.feature.0.weight" in state_dict'

**Comment by Eric-mingjie** [comment]
I try the code myself. There is not any problem with the code itself.

I think the problem is that the format of `checkpoint.pth.tar' and `model' is not the same. One of them is a DataParrell object. Please make sure they conform to the same object type.

**Comment by nepulhl** [comment]
Thanks for your nice sharing!
there is a fault when i run the file of vggprune.py.
Traceback (most recent call last):
  File "vggprune.py", line 142, in <module>
    m1.weight.data = m0.weight.data[idx1.tolist()].clone()
TypeError: indexing a tensor with an object of type list. The only supported types are integers, slices, numpy scalars and torch.cuda.LongTensor or torch.cuda.ByteTensor as the only argument.

**Comment by Eric-mingjie** [comment]
@nepulhl are you using Pytorch 0.3.1? Our code is developed based on Pytorch version 0.3.1.

**Comment by nepulhl** [comment]
@Eric-mingjie Thank you,I have sloved the problem by updating Pytorch.
