### ISSUE TITLE
How to set the number of channels for convolution layer input after Channel-level Sparsity

### ISSUE THREAD

**Issue by InstantWindy** [Eric-mingjie/network-slimming#6]
Hi! After channel_selection is invoked,the places in `indexes` which correpond to the channels to be pruned will be set to 0. So,the number of channels of feature map changes. After pruning, how do you determine the number of channels for feature map?

**Comment by Eric-mingjie** [comment]
I am not sure if I understand your question. After pruning, the number of channels for feature map is fixed.
