### ISSUE TITLE
关于FLOPs计算

### ISSUE THREAD

**Issue by arthur0219** [Eric-mingjie/network-slimming#60]
作者您好，想问一下对剪枝后的模型，怎么查看参数量和FLOPs呢？在剪枝后模型上用普通的指令会报错

**Comment by Eric-mingjie** [comment]
https://github.com/Eric-mingjie/rethinking-network-pruning/blob/master/imagenet/l1-norm-pruning/compute_flops.py

**Comment by arthur0219** [comment]
Ok, thanks a lot
