### ISSUE TITLE
How can finetune pruned models?

### ISSUE THREAD

**Issue by HaiPhan1991** [Eric-mingjie/network-slimming#7]
Hi @Eric-mingjie, 

Thanks for your great implementation. I want to finetune my pruned network but in your main.py, the error show that there is no flag: --refine. Could you show me how to use that?

Thanks,
Hai

**Comment by Eric-mingjie** [comment]
Hi, thanks for your interest in our code.

`--refine` is defined in [here](https://github.com/Eric-mingjie/network-slimming/blob/master/main.py#L23) in `main.py`.

The way to finetune pruned model is given [here](https://github.com/Eric-mingjie/network-slimming#fine-tune).

**Comment by HaiPhan1991** [comment]
Thanks for your reply. It would be very helpful for me.
