### ISSUE TITLE
关于thersh

### ISSUE THREAD

**Issue by bright2311** [Eric-mingjie/network-slimming#70]
Hello,Phd Sun.
Have you met the condition some layer would be pruned wholly when  all the related BN values are lower than the threshold?
Is there some method given to deal with it?
Thank you,

**Comment by Eric-mingjie** [comment]
Yeah, in that case, for VGG style network, there is nothing you can do except reduce the prune ratio. For ResNet and DenseNet style network, you can use [mask-implementation](https://github.com/Eric-mingjie/network-slimming/tree/master/mask-impl) but it does not reduce the actual network size.

**Comment by bright2311** [comment]
> l

OK.Get it.
