### ISSUE TITLE
Where is the model stored after ''Train with Sparsity'' or ''Baseline''?

### ISSUE THREAD

**Issue by BokaiLIAN** [Eric-mingjie/network-slimming#8]
After training, is there any ckpt file? If there is , plz give me the dir .

**Comment by BokaiLIAN** [comment]
about the argu --refine?

**Comment by Eric-mingjie** [comment]
It is stored in `args.save` directory. See [here](https://github.com/Eric-mingjie/network-slimming/blob/master/main.py#L183).

**Comment by BokaiLIAN** [comment]
> It is stored in `args.save` directory. See [here](https://github.com/Eric-mingjie/network-slimming/blob/master/main.py#L183).

i see the default of arg.save is ''/logs''.  Thanks for your reply,

**Comment by BokaiLIAN** [comment]
> It is stored in `args.save` directory. See [here](https://github.com/Eric-mingjie/network-slimming/blob/master/main.py#L183).

Hello, I have **retrain the model** to get a complete ckpt and the training process read normal
`Test set: Average loss: 0.2486, Accuracy: 9413/10000 (94.0%)`

**But** still encounter some problem during pruning when setting the  model path argu as  
`--model  ./logs/checkpoint.pth.tar`   

**And it shows**
`=> loading checkpoint './logs/checkpoint.pth.tar'
=> loaded checkpoint './logs/checkpoint.pth.tar' (epoch 160) Prec1: 0.000000
Traceback (most recent call last):
  File "denseprune.py", line 73, in <module>
    mask = weight_copy.gt(thre).float().cuda()
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'
`

**Comment by Eric-mingjie** [comment]
Which version of Pytorch are you using? Our code is developed on Pytorch 3.1.

**Comment by cardwing** [comment]
In my case, replacing `mask = weight_copy.gt(thre).float().cuda()` with `mask = weight_copy.gt(thre.cuda()).float().cuda()` works.
